version: "3.7"
services:
  #database container
  db:
    container_name: db
    environment:
<<<<<<< HEAD
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mysecretpassword
    image: postgres:13
=======
      - POSTGRES_USER=$DB_USER
      - POSTGRES_PASSWORD=$DB_PASSWORD
      - POSTGRES_DB=$DB_NAME
>>>>>>> f3d09d43a8bf83492b61d31605cd9782fe503f8c
    ports:
      - "5432:5432"
    volumes:
      - ./db/data:/var/lib/postgresql/data
    env_file:
      - ./docker.env
    networks:
      - app-network
    restart: always

  #backend container
  apis:
    container_name: apis
    build: ./apis
    ports:
      - "5000:5000"
    volumes:
      - ./apis:/usr/src/app
      - /app/node_modules
<<<<<<< HEAD
    env_file:
      - ./docker.env
    networks:
      - app-network
    depends_on:
      - db

  #frontend container
  frontend:
    container_name: frontend
=======
  frontend_new:
>>>>>>> f3d09d43a8bf83492b61d31605cd9782fe503f8c
    build: ./frontend
    ports:
      - "80:3000"
    volumes:
      - ./frontend:/usr/src/client
      - /client/node_modules
    env_file:
      - ./docker.env
    networks:
      - app-network
    depends_on:
      - apis
    stdin_open: true
<<<<<<< HEAD

  #database admin
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    ports:
      - 8000:80
    depends_on:
      - db
    env_file:
      - ./docker.env
    networks:
      - app-network
# define network
networks:
  app-network:
=======
  pgadmin:
   image: dpage/pgadmin4
   restart: always
   environment:
    - PGADMIN_DEFAULT_EMAIL=$PGADMIN_EMAIL
    - PGADMIN_DEFAULT_PASSWORD=$PGADMIN_PASSWORD
   ports:
     - $PGADMIN_PORT:$PGADMIN_PORT
   depends_on:
    - db
>>>>>>> f3d09d43a8bf83492b61d31605cd9782fe503f8c
