version: "3.8"

services:

#database container
  db:
    image: postgres:13.1
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - $DB_PORT:$DB_PORT
    volumes:
      - ./db/data:/var/lib/postgresql/data
    restart: always
    networks:
      - app-network

#backend container
  apis:
    build: ./apis
    ports:
      - ${API_PORT}:${API_PORT}
    volumes:
      - ./apis:/usr/src/app
      - /app/node_modules
    networks:
    - app-network
    depends_on:
      - db
  
#frontend container
  frontend:
    build: ./frontend
    ports:
      - $EX_CLIENT_PORT:$CLIENT_PORT
    volumes:
      - ./frontend:/usr/src/client
      - /client/node_modules
    networks:
      - app-network
    depends_on:
      - apis
    stdin_open: true


#database admin
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    ports:
      - ${ADMIN_PORT}:80
    environment:
      - PGADMIN_DEFAULT_EMAIL=${ADMIN_USER}
      - PGADMIN_DEFAULT_PASSWORD=${ADMIN_PASSWORD}
    depends_on:
      - db
    networks:
      - app-network

# define network
networks:
  app-network:

