version: "3.7"
services:
  #database container
  db:
    container_name: db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    image: postgres:13
    ports:
      - "5432:5432"
    volumes:
      - ./db/data:/var/lib/postgresql/data
    env_file:
      - ./docker.env
    networks:
      - app-network
    restart: always

  #backend container
  apis:
    container_name: apis
    build: ./apis
    ports:
      - "5000:5000"
    volumes:
      - ./apis:/usr/src/app
      - /app/node_modules
    env_file:
      - ./docker.env
    networks:
      - app-network
    depends_on:
      - db

  #frontend container
  frontend:
    container_name: frontend
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/usr/src/client
      - /client/node_modules
    env_file:
      - ./docker.env
    networks:
      - app-network
    depends_on:
      - apis
    stdin_open: true

# define network
networks:
  app-network:
