version: "3.7"
services:
  db:
    image: postgres:13.1
    environment:
      - POSTGRES_USER=$DB_USER
      - POSTGRES_PASSWORD=$DB_PASSWORD
      - POSTGRES_DB=$DB_NAME
    ports:
      - $DB_PORT:$DB_PORT
    volumes:
      - ./db/data:/var/lib/postgresql/data
    restart: always
    command: -p $DB_PORT
  apis:
    depends_on:
      - db
    build: ./apis
    environment:
      - NODE_ENV=$API_NODE_ENV
      - PORT=$API_PORT
      - PGHOST=db
      - PGPORT=$DB_PORT
      - PGUSER=$DB_USER
      - PGPASSWORD=$DB_PASSWORD
      - PGDATABASE=$DB_NAME
    ports:
      - $API_PORT:$API_PORT
    volumes:
      - ./apis:/usr/src/app
      - /app/node_modules
  frontend:
    build: ./frontend
    environment:
      - NODE_ENV=$CLIENT_NODE_ENV
      - PORT=$CLIENT_PORT
      - BASE_APIS_URL
    ports:
      - $EX_CLIENT_PORT:$CLIENT_PORT
    volumes:
      - ./frontend:/usr/src/client
      - /client/node_modules
    stdin_open: true
  pgadmin:
   image: dpage/pgadmin4
   restart: always
   environment:
    - PGADMIN_DEFAULT_EMAIL=$PGADMIN_EMAIL
    - PGADMIN_DEFAULT_PASSWORD=$PGADMIN_PASSWORD
   ports:
     - $PGADMIN_PORT:$PGADMIN_PORT
   depends_on:
    - db
